### ISSUE TITLE
似乎不支持flutter2.0？

### ISSUE THREAD

**Issue by Owenli0202** [liujiakuoyx/leak_detector#1]

**Comment by liujiakuoyx** [comment]
将会马上支持2.0.增加空安全

**Comment by Owenli0202** [comment]
期待

**Comment by liujiakuoyx** [comment]
已经支持flutter2以及空安全，但是经过测试，真机调试时，在最新版本的flutter上存在**Single Client Mode**的问题。

**Comment by liujiakuoyx** [comment]
您好，我找到了vm_service的Single Client Mode模式导致插件无法正常工作的问题，详情如下图所示：
![image](https://user-images.githubusercontent.com/22370823/119317791-14d70f00-bcab-11eb-9430-f0d8b1c86e09.png)

**Comment by Owenli0202** [comment]
按照你的方法终于可以在flutter2.0上面使用了，但是能不能优化成基于路由的方式？你现在是用StateLeakMixin来检测，我的页面有时基于stateless的

**Comment by liujiakuoyx** [comment]
感谢您的建议，已经有计划这样做了。

**Comment by liujiakuoyx** [comment]
你可以使用1.0.1版本，使用上与之前有些区别，请参考 [README](https://github.com/liujiakuoyx/leak_detector/blob/main/README_zh-CN.md)
