### ISSUE TITLE
為什麼在單純進出頁面會有memory leak

### ISSUE THREAD

**Issue by jess0507** [liujiakuoyx/leak_detector#12]
我點選第一個按鈕，單純進入和退出第一個頁面，沒有新增任何東西但還是偵測到洩漏？

![photo_2022-11-13 21 54 26](https://user-images.githubusercontent.com/5594453/201525430-1294268f-0564-4d7d-abd6-0fcf727b90dd.jpeg)
![photo_2022-11-13 21 54 24](https://user-images.githubusercontent.com/5594453/201525440-ed1bbf14-3581-4f91-aa52-41a625e4deb0.jpeg)

**Comment by liujiakuoyx** [comment]
因为我在第二个页面退出的时候调用的代码模拟了内存泄漏，`this`对象被当做返回值引用了，导致`LeakPage1`出现了泄漏
![image](https://user-images.githubusercontent.com/22370823/205243890-b8d6bc53-7008-431b-b758-6e4e7bb4de20.png)
