### ISSUE TITLE
貌似新版本运行example已经不会报内存泄露了？

### ISSUE THREAD

**Issue by Hilbert2048** [liujiakuoyx/leak_detector#16]
Performing hot restart...
Syncing files to device iPhone 15 Pro...
Restarted application in 954ms.
flutter: DetectorEventType.addObject, /p1(78023448)
flutter: DetectorEventType.addObject, /p1(78023448)
flutter: DetectorEventType.check, /p1(78023448)
flutter: DetectorEventType.startGC, null
flutter: DetectorEventType.endGc, null

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.16.0-0.3.pre, on macOS 14.0 23A344 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)

**Comment by liujiakuoyx** [comment]
十分抱歉，可能随着Flutter的更新，部分底层逻辑修改了；也可能是我的代码好久没更新，在新版本上检测不到了，具体的还辛苦您自己看下，我这边已经好久不做Flutter了，这个插件比较简单没多少代码，可以fork自己改一下
