### ISSUE TITLE
Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by GP-Moon** [liujiakuoyx/leak_detector#3]
Undefined symbols for architecture arm64:
      "value witness table for Builtin.UnknownObject", referenced from:
          full type metadata for leak_detector.SwiftLeakDetectorPlugin in libleak_detector.a(SwiftLeakDetectorPlugin.o)
      "__swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements", referenced from:
          __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_leak_detector in libleak_detector.a(SwiftLeakDetectorPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_leak_detector)
      "__swift_FORCE_LOAD_$_swiftCompatibility51", referenced from:
          __swift_FORCE_LOAD_$_swiftCompatibility51_$_leak_detector in libleak_detector.a(SwiftLeakDetectorPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility51_$_leak_detector)
      "__swift_FORCE_LOAD_$_swiftCompatibility50", referenced from:
          __swift_FORCE_LOAD_$_swiftCompatibility50_$_leak_detector in libleak_detector.a(SwiftLeakDetectorPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility50_$_leak_detector)
      "__swift_FORCE_LOAD_$_swiftQuartzCore", referenced from:
          __swift_FORCE_LOAD_$_swiftQuartzCore_$_leak_detector in libleak_detector.a(SwiftLeakDetectorPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftQuartzCore_$_leak_detector)
      "__swift_FORCE_LOAD_$_swiftCoreImage", referenced from:
          __swift_FORCE_LOAD_$_swiftCoreImage_$_leak_detector in libleak_detector.a(SwiftLeakDetectorPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreImage_$_leak_detector)
      "__swift_FORCE_LOAD_$_swiftCoreGraphics", referenced from:
          __swift_FORCE_LOAD_$_swiftCoreGraphics_$_leak_detector in libleak_detector.a(SwiftLeakDetectorPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreGraphics_$_leak_detector)
      "__swift_FORCE_LOAD_$_swiftCoreFoundation", referenced from:
          __swift_FORCE_LOAD_$_swiftCoreFoundation_$_leak_detector in libleak_detector.a(SwiftLeakDetectorPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreFoundation_$_leak_detector)
      "_swift_getObjectType", referenced from:
          static leak_detector.SwiftLeakDetectorPlugin.register(with: __C.FlutterPluginRegistrar) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
      "__swift_FORCE_LOAD_$_swiftUIKit", referenced from:
          __swift_FORCE_LOAD_$_swiftUIKit_$_leak_detector in libleak_detector.a(SwiftLeakDetectorPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftUIKit_$_leak_detector)
      "_swift_allocObject", referenced from:
          @objc leak_detector.SwiftLeakDetectorPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
      "static (extension in Foundation):Swift.String._unconditionallyBridgeFromObjectiveC(__C.NSString?) -> Swift.String", referenced from:
          leak_detector.SwiftLeakDetectorPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
      "_swift_getInitializedObjCClass", referenced from:
          type metadata accessor for __C.FlutterMethodChannel in libleak_detector.a(SwiftLeakDetectorPlugin.o)
          type metadata accessor for leak_detector.SwiftLeakDetectorPlugin in libleak_detector.a(SwiftLeakDetectorPlugin.o)
          leak_detector.SwiftLeakDetectorPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
      "__swift_FORCE_LOAD_$_swiftFoundation", referenced from:
          __swift_FORCE_LOAD_$_swiftFoundation_$_leak_detector in libleak_detector.a(SwiftLeakDetectorPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftFoundation_$_leak_detector)
      "__swift_FORCE_LOAD_$_swiftCoreAudio", referenced from:
          __swift_FORCE_LOAD_$_swiftCoreAudio_$_leak_detector in libleak_detector.a(SwiftLeakDetectorPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreAudio_$_leak_detector)
      "static Swift.String.+ infix(Swift.String, Swift.String) -> Swift.String", referenced from:
          leak_detector.SwiftLeakDetectorPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
      "__swift_FORCE_LOAD_$_swiftDarwin", referenced from:
          __swift_FORCE_LOAD_$_swiftDarwin_$_leak_detector in libleak_detector.a(SwiftLeakDetectorPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftDarwin_$_leak_detector)
      "_swift_unknownObjectRelease", referenced from:
          static leak_detector.SwiftLeakDetectorPlugin.register(with: __C.FlutterPluginRegistrar) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
          @nonobjc __C.FlutterMethodChannel.__allocating_init(name: Swift.String, binaryMessenger: __C.FlutterBinaryMessenger) -> __C.FlutterMethodChannel in libleak_detector.a(SwiftLeakDetectorPlugin.o)
          @objc static leak_detector.SwiftLeakDetectorPlugin.register(with: __C.FlutterPluginRegistrar) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
          reabstraction thunk helper from @escaping @callee_unowned @convention(block) (@unowned Swift.AnyObject?) -> () to @escaping @callee_guaranteed (@in_guaranteed Any?) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
      "__swift_FORCE_LOAD_$_swiftDispatch", referenced from:
          __swift_FORCE_LOAD_$_swiftDispatch_$_leak_detector in libleak_detector.a(SwiftLeakDetectorPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftDispatch_$_leak_detector)
      "_swift_release", referenced from:
          leak_detector.SwiftLeakDetectorPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
          ___swift_destroy_boxed_opaque_existential_0 in libleak_detector.a(SwiftLeakDetectorPlugin.o)
          @objc leak_detector.SwiftLeakDetectorPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
      "_swift_deallocObject", referenced from:
          l_objectdestroy in libleak_detector.a(SwiftLeakDetectorPlugin.o)
      "__swift_FORCE_LOAD_$_swiftMetal", referenced from:
          __swift_FORCE_LOAD_$_swiftMetal_$_leak_detector in libleak_detector.a(SwiftLeakDetectorPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftMetal_$_leak_detector)
      "_swift_retain", referenced from:
          leak_detector.SwiftLeakDetectorPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
      "__swift_FORCE_LOAD_$_swiftObjectiveC", referenced from:
          __swift_FORCE_LOAD_$_swiftObjectiveC_$_leak_detector in libleak_detector.a(SwiftLeakDetectorPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftObjectiveC_$_leak_detector)
      "_swift_unknownObjectRetain", referenced from:
          @objc static leak_detector.SwiftLeakDetectorPlugin.register(with: __C.FlutterPluginRegistrar) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
      "Swift._bridgeAnythingToObjectiveC<A>(A) -> Swift.AnyObject", referenced from:
          reabstraction thunk helper from @escaping @callee_unowned @convention(block) (@unowned Swift.AnyObject?) -> () to @escaping @callee_guaranteed (@in_guaranteed Any?) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
      "_swift_getObjCClassMetadata", referenced from:
          type metadata accessor for __C.FlutterMethodChannel in libleak_detector.a(SwiftLeakDetectorPlugin.o)
          @objc static leak_detector.SwiftLeakDetectorPlugin.register(with: __C.FlutterPluginRegistrar) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
      "(extension in Foundation):Swift.String._bridgeToObjectiveC() -> __C.NSString", referenced from:
          @nonobjc __C.FlutterMethodChannel.__allocating_init(name: Swift.String, binaryMessenger: __C.FlutterBinaryMessenger) -> __C.FlutterMethodChannel in libleak_detector.a(SwiftLeakDetectorPlugin.o)
      "_swift_getObjCClassFromMetadata", referenced from:
          @nonobjc __C.FlutterMethodChannel.__allocating_init(name: Swift.String, binaryMessenger: __C.FlutterBinaryMessenger) -> __C.FlutterMethodChannel in libleak_detector.a(SwiftLeakDetectorPlugin.o)
      "__swift_FORCE_LOAD_$_swiftCoreMedia", referenced from:
          __swift_FORCE_LOAD_$_swiftCoreMedia_$_leak_detector in libleak_detector.a(SwiftLeakDetectorPlugin.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreMedia_$_leak_detector)
      "type metadata for Swift.String", referenced from:
          leak_detector.SwiftLeakDetectorPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
      "_swift_bridgeObjectRelease", referenced from:
          @nonobjc __C.FlutterMethodChannel.__allocating_init(name: Swift.String, binaryMessenger: __C.FlutterBinaryMessenger) -> __C.FlutterMethodChannel in libleak_detector.a(SwiftLeakDetectorPlugin.o)
          leak_detector.SwiftLeakDetectorPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
      "Swift.String.init(_builtinStringLiteral: Builtin.RawPointer, utf8CodeUnitCount: Builtin.Word, isASCII: Builtin.Int1) -> Swift.String", referenced from:
          static leak_detector.SwiftLeakDetectorPlugin.register(with: __C.FlutterPluginRegistrar) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
          leak_detector.SwiftLeakDetectorPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in libleak_detector.a(SwiftLeakDetectorPlugin.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by liujiakuoyx** [comment]
I think it has something to do with the configuration of your iOS project
