### ISSUE TITLE
how to set --no-dds in add-to-app

### ISSUE THREAD

**Issue by shingohu** [liujiakuoyx/leak_detector#8]
Add the --disable-dds parameter after flutter run to turn off the DDS. After testing, this will not cause any impact on debugging

My flutter module is add-to-app，so how can i set --no-dds

**Comment by liujiakuoyx** [comment]
Please try to see if `flutter build aar` supports the `--no-dds` argument

**Comment by liujiakuoyx** [comment]
`flutter build` dds are not enabled by default, so you don't need to add any arguments. `flutter attach` supports adding the `--no-dds` argument.
![image](https://user-images.githubusercontent.com/22370823/166891637-131cb97d-55fb-49ec-bc38-64eefc1236fb.png)
